import { CaptionStyle, StylePresetId } from '../types';

export interface StylePresetDefinition {
  id: StylePresetId;
  name: string;
  description: string;
  previewSample: string;
  badgeColor: string;
  style: CaptionStyle;
}

export const STYLE_PRESETS: StylePresetDefinition[] = [
  {
    id: 'viral',
    name: 'Viral Pop',
    description: 'Ultra bold white text with strong black stroke, drop shadow, and punchy contrast.',
    previewSample: 'THIS IS AMAZING!',
    badgeColor: '#F5B82E',
    style: {
      fontFamily: 'Impact, -apple-system, sans-serif',
      fontSize: 54,
      fontWeight: 900,
      textColor: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 4,
      shadowColor: 'rgba(0, 0, 0, 0.95)',
      shadowBlur: 10,
      shadowOffsetX: 3,
      shadowOffsetY: 5,
      backgroundColor: 'transparent',
      paddingX: 20,
      paddingY: 10,
      borderRadius: 12,
      textAlign: 'center',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 80,
      highlightColor: '#F5B82E',
      highlightNormalColor: '#FFFFFF',
      highlightScale: 1.15,
      highlightBackground: 'rgba(0, 0, 0, 0.4)',
      highlightUnderline: false,
      highlightGlow: true,
      highlightMode: 'scale',
    },
  },
  {
    id: 'karaoke',
    name: 'Karaoke Active',
    description: 'Sequentially highlighted words with golden glow and active word enlargement.',
    previewSample: 'Sing along sequentially',
    badgeColor: '#10B981',
    style: {
      fontFamily: 'system-ui, -apple-system, sans-serif',
      fontSize: 48,
      fontWeight: 800,
      textColor: '#E2E8F0',
      strokeColor: 'rgba(0,0,0,0.85)',
      strokeWidth: 3,
      shadowColor: 'rgba(0, 0, 0, 0.8)',
      shadowBlur: 8,
      shadowOffsetX: 2,
      shadowOffsetY: 4,
      backgroundColor: 'rgba(15, 23, 42, 0.65)',
      paddingX: 28,
      paddingY: 14,
      borderRadius: 16,
      textAlign: 'center',
      letterSpacing: 0.5,
      textTransform: 'none',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 78,
      highlightColor: '#F5B82E',
      highlightNormalColor: '#94A3B8',
      highlightScale: 1.14,
      highlightBackground: 'rgba(245, 184, 46, 0.25)',
      highlightUnderline: false,
      highlightGlow: true,
      highlightMode: 'color',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal Clean',
    description: 'Elegant sans-serif inside a subtle translucent dark pill. Clean and non-intrusive.',
    previewSample: 'Minimalist clarity',
    badgeColor: '#64748B',
    style: {
      fontFamily: 'Helvetica, Arial, sans-serif',
      fontSize: 36,
      fontWeight: 600,
      textColor: '#FFFFFF',
      strokeColor: 'transparent',
      strokeWidth: 0,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      backgroundColor: 'rgba(11, 13, 16, 0.78)',
      paddingX: 24,
      paddingY: 12,
      borderRadius: 9999,
      textAlign: 'center',
      letterSpacing: 0,
      textTransform: 'none',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 84,
      highlightColor: '#60A5FA',
      highlightNormalColor: '#E2E8F0',
      highlightScale: 1.05,
      highlightBackground: 'transparent',
      highlightUnderline: true,
      highlightGlow: false,
      highlightMode: 'color',
    },
  },
  {
    id: 'podcast',
    name: 'Podcast Editorial',
    description: 'Warm, readable editorial typography crafted for dialogue, interviews, and reels.',
    previewSample: 'Intelligent conversation',
    badgeColor: '#F97316',
    style: {
      fontFamily: 'Georgia, serif',
      fontSize: 42,
      fontWeight: 700,
      textColor: '#FFFBEB',
      strokeColor: 'rgba(0, 0, 0, 0.6)',
      strokeWidth: 2,
      shadowColor: 'rgba(0, 0, 0, 0.75)',
      shadowBlur: 6,
      shadowOffsetX: 1,
      shadowOffsetY: 3,
      backgroundColor: 'rgba(28, 25, 23, 0.85)',
      paddingX: 30,
      paddingY: 14,
      borderRadius: 14,
      textAlign: 'center',
      letterSpacing: 0.2,
      textTransform: 'none',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 80,
      highlightColor: '#FBBF24',
      highlightNormalColor: '#D6D3D1',
      highlightScale: 1.08,
      highlightBackground: 'rgba(245, 158, 11, 0.2)',
      highlightUnderline: false,
      highlightGlow: false,
      highlightMode: 'background',
    },
  },
  {
    id: 'news',
    name: 'News Broadcast',
    description: 'High urgency lower-third headline style with crisp red/yellow contrast and sharp borders.',
    previewSample: 'BREAKING NEWS UPDATE',
    badgeColor: '#EF4444',
    style: {
      fontFamily: 'Arial, sans-serif',
      fontSize: 40,
      fontWeight: 800,
      textColor: '#FFFFFF',
      strokeColor: '#7F1D1D',
      strokeWidth: 2,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 6,
      shadowOffsetX: 2,
      shadowOffsetY: 2,
      backgroundColor: 'rgba(185, 28, 28, 0.92)',
      paddingX: 32,
      paddingY: 12,
      borderRadius: 4,
      textAlign: 'left',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      positionPreset: 'bottom-left',
      posX: 15,
      posY: 85,
      highlightColor: '#FEF08A',
      highlightNormalColor: '#FFFFFF',
      highlightScale: 1.06,
      highlightBackground: 'rgba(0,0,0,0.5)',
      highlightUnderline: true,
      highlightGlow: true,
      highlightMode: 'color',
    },
  },
  {
    id: 'cinematic',
    name: 'Cinematic Letterbox',
    description: 'Wide tracking, elegant classic serif font with soft ambient drop-shadow. Film grade.',
    previewSample: 'A cinematic voyage',
    badgeColor: '#A855F7',
    style: {
      fontFamily: 'Times New Roman, Georgia, serif',
      fontSize: 38,
      fontWeight: 500,
      textColor: '#F8FAFC',
      strokeColor: 'transparent',
      strokeWidth: 0,
      shadowColor: 'rgba(0, 0, 0, 0.9)',
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      backgroundColor: 'transparent',
      paddingX: 24,
      paddingY: 10,
      borderRadius: 0,
      textAlign: 'center',
      letterSpacing: 4,
      textTransform: 'none',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 85,
      highlightColor: '#E2E8F0',
      highlightNormalColor: '#94A3B8',
      highlightScale: 1.04,
      highlightBackground: 'transparent',
      highlightUnderline: false,
      highlightGlow: true,
      highlightMode: 'color',
    },
  },
  {
    id: 'neon',
    name: 'Cyber Neon Glow',
    description: 'Electrifying neon aura with vibrant cyan glow and dark backdrop for high tech reels.',
    previewSample: 'CYBERPUNK VISION',
    badgeColor: '#06B6D4',
    style: {
      fontFamily: 'Trebuchet MS, -apple-system, sans-serif',
      fontSize: 46,
      fontWeight: 800,
      textColor: '#E0F2FE',
      strokeColor: '#0891B2',
      strokeWidth: 2,
      shadowColor: '#06B6D4',
      shadowBlur: 22,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      backgroundColor: 'rgba(8, 14, 26, 0.85)',
      paddingX: 26,
      paddingY: 12,
      borderRadius: 12,
      textAlign: 'center',
      letterSpacing: 1.8,
      textTransform: 'uppercase',
      positionPreset: 'center',
      posX: 50,
      posY: 50,
      highlightColor: '#38BDF8',
      highlightNormalColor: '#7DD3FC',
      highlightScale: 1.12,
      highlightBackground: 'rgba(14, 165, 233, 0.3)',
      highlightUnderline: false,
      highlightGlow: true,
      highlightMode: 'glow',
    },
  },
  {
    id: 'bold-social',
    name: 'Bold Social Punch',
    description: 'Vivid high-energy italicized block font designed for TikTok, YouTube Shorts and Reels.',
    previewSample: 'DON\'T MISS THIS!',
    badgeColor: '#EC4899',
    style: {
      fontFamily: 'Impact, Arial Black, sans-serif',
      fontSize: 52,
      fontWeight: 900,
      textColor: '#FEF08A',
      strokeColor: '#18181B',
      strokeWidth: 5,
      shadowColor: 'rgba(0, 0, 0, 0.95)',
      shadowBlur: 8,
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      backgroundColor: 'transparent',
      paddingX: 20,
      paddingY: 10,
      borderRadius: 8,
      textAlign: 'center',
      letterSpacing: 1.0,
      textTransform: 'uppercase',
      positionPreset: 'center',
      posX: 50,
      posY: 45,
      highlightColor: '#F43F5E',
      highlightNormalColor: '#FEF08A',
      highlightScale: 1.18,
      highlightBackground: 'rgba(0,0,0,0.6)',
      highlightUnderline: false,
      highlightGlow: true,
      highlightMode: 'scale',
    },
  },
  {
    id: 'corporate',
    name: 'Clean Corporate',
    description: 'Balanced slate & azure tones with refined subtle borders for professional enterprise videos.',
    previewSample: 'Quarterly Strategic Growth',
    badgeColor: '#3B82F6',
    style: {
      fontFamily: 'Verdana, Geneva, sans-serif',
      fontSize: 38,
      fontWeight: 600,
      textColor: '#F8FAFC',
      strokeColor: 'transparent',
      strokeWidth: 0,
      shadowColor: 'rgba(0, 0, 0, 0.4)',
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      backgroundColor: 'rgba(15, 23, 42, 0.88)',
      paddingX: 28,
      paddingY: 12,
      borderRadius: 8,
      textAlign: 'center',
      letterSpacing: 0.4,
      textTransform: 'none',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 82,
      highlightColor: '#38BDF8',
      highlightNormalColor: '#CBD5E1',
      highlightScale: 1.06,
      highlightBackground: 'rgba(56, 189, 248, 0.2)',
      highlightUnderline: true,
      highlightGlow: false,
      highlightMode: 'color',
    },
  },
  {
    id: 'luxury',
    name: 'Luxury Champagne',
    description: 'Refined serif typography paired with warm champagne gold accents and subtle letter-spacing.',
    previewSample: 'Timeless Elegance',
    badgeColor: '#D97706',
    style: {
      fontFamily: 'Georgia, Times New Roman, serif',
      fontSize: 40,
      fontWeight: 500,
      textColor: '#FDE68A',
      strokeColor: 'rgba(69, 26, 3, 0.8)',
      strokeWidth: 1.5,
      shadowColor: 'rgba(0, 0, 0, 0.85)',
      shadowBlur: 10,
      shadowOffsetX: 2,
      shadowOffsetY: 4,
      backgroundColor: 'rgba(26, 18, 11, 0.82)',
      paddingX: 32,
      paddingY: 14,
      borderRadius: 16,
      textAlign: 'center',
      letterSpacing: 2.2,
      textTransform: 'none',
      positionPreset: 'bottom-center',
      posX: 50,
      posY: 80,
      highlightColor: '#F59E0B',
      highlightNormalColor: '#FEF3C7',
      highlightScale: 1.08,
      highlightBackground: 'rgba(217, 119, 6, 0.25)',
      highlightUnderline: false,
      highlightGlow: true,
      highlightMode: 'color',
    },
  },
];

export function getStylePreset(id: string): CaptionStyle {
  const found = STYLE_PRESETS.find((p) => p.id === id);
  if (found) return { ...found.style };
  return { ...STYLE_PRESETS[0].style };
}

export const SYSTEM_FONTS = [
  { name: 'Impact (Viral/Punchy)', value: 'Impact, sans-serif' },
  { name: 'Arial (Clean Sans)', value: 'Arial, sans-serif' },
  { name: 'Helvetica (Modern Neutral)', value: 'Helvetica, Arial, sans-serif' },
  { name: 'System UI (Native OS)', value: 'system-ui, -apple-system, sans-serif' },
  { name: 'Verdana (High Readability)', value: 'Verdana, Geneva, sans-serif' },
  { name: 'Georgia (Warm Serif)', value: 'Georgia, serif' },
  { name: 'Times New Roman (Editorial)', value: 'Times New Roman, serif' },
  { name: 'Trebuchet MS (Dynamic)', value: 'Trebuchet MS, sans-serif' },
  { name: 'Courier New (Monospace)', value: 'Courier New, monospace' },
];
